name: Deploy Site TeraNex

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH=$PATH:/usr/bin:/usr/local/bin
            cd /home/teranex/repo
            git config --global --add safe.directory /home/teranex/repo
            git pull origin prod
            cd frontend
            npm install
            npm run build
            cp -r dist/* /home/teranex/htdocs/www.teranex.inf.br/